version: '3.5'
services:
  terminalserver:
    image: thyarles/xrdp-ride:18.04
    container_name: xrdp
    hostname: www.businesswebbing.com
    restart: always
    shm_size: 1g
    environment:
       PASSWORDHASH: $$1$$z53Cg/fV$$06o379IvIOxj/ESruVKrG1
       IDLETIME: 11
    ports:
      - "8022:3389"
    #  - "2222:22"
    volumes:
    #  - ssh:/etc/ssh/
      - /home/rdp/:/home/

#volumes:
#  ssh:
